language: csharp
dist: xenial
mono: none
sudo: required
services:
  - docker
script:
  - docker build -t mcr.microsoft.com/dotnet/core/aspnet:3.1 .
  - docker run --rm -it --name mcr.microsoft.com/dotnet/core/aspnet mcr.microsoft.com/dotnet/core/aspnet:3.1