// Generated by the Blazor I18n Text compiler
namespace CatchMe.Web.Client.I18nText
{
    public partial class site : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Geolocation app to find your friends"</summary>
        public string altlogo;

        /// <summary>"Geolocation app to find your friends"</summary>
        public string header;

        /// <summary>"Login"</summary>
        public string login;

        /// <summary>"Logout"</summary>
        public string logout;

        /// <summary>"Find your friends"</summary>
        public string subheader;
    }
}
